drop table LOTTERY_UNION_LOTTO;
-- CREATE TABLE
CREATE TABLE LOTTERY_UNION_LOTTO
(
  LUCKY_NUMBER_ID   NUMBER(9) NOT NULL PRIMARY KEY,
  LOTTERY_DATE     DATE  NOT NULL,
  LOTTERY_ISSUE     VARCHAR2(60) NOT NULL,
  LOTTERY_TYPE       NUMBER(6)  NOT NULL,
  RED_NUMBER1   NUMBER(3)  NOT NULL,
  RED_NUMBER1_STATUS     CHAR(1),
  RED_NUMBER2      NUMBER(3) NOT NULL,
  RED_NUMBER2_STATUS       CHAR(1),
  RED_NUMBER3      NUMBER(3)  NOT NULL,
  RED_NUMBER3_STATUS     CHAR(1),
  RED_NUMBER4          NUMBER(3)  NOT NULL,
  RED_NUMBER4_STATUS      CHAR(1),
  RED_NUMBER5          NUMBER(3)  NOT NULL,
  RED_NUMBER5_STATUS   CHAR(1),
  RED_NUMBER6   NUMBER(3)  NOT NULL,
  RED_NUMBER6_STATUS CHAR(1),
  BLUE_NUMBER NUMBER(3)  NOT NULL,
  BLUE_NUMBER_STATUS CHAR(1),
  PART_ID      NUMBER(3) DEFAULT TO_NUMBER(TO_CHAR(SYSDATE,'MM')) NOT NULL
)

PARTITION BY LIST (PART_ID)
(
  PARTITION P1 VALUES (1)
  TABLESPACE TAB_CC
  PCTFREE 10
  INITRANS 1
  MAXTRANS 255,
  PARTITION P2 VALUES (2)
  TABLESPACE TAB_CC
  PCTFREE 10
  INITRANS 1
  MAXTRANS 255,
  PARTITION P3 VALUES (3)
  TABLESPACE TAB_CC
  PCTFREE 10
  INITRANS 1
  MAXTRANS 255,
  PARTITION P4 VALUES (4)
  TABLESPACE TAB_CC
  PCTFREE 10
  INITRANS 1
  MAXTRANS 255,
  PARTITION P5 VALUES (5)
  TABLESPACE TAB_CC
  PCTFREE 10
  INITRANS 1
  MAXTRANS 255,
  PARTITION P6 VALUES (6)
  TABLESPACE TAB_CC
  PCTFREE 10
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
  INITIAL 8M
  NEXT 1M
  MINEXTENTS 1
  MAXEXTENTS UNLIMITED
  ),
  PARTITION P7 VALUES (7)
  TABLESPACE TAB_CC
  PCTFREE 10
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
  INITIAL 8M
  NEXT 1M
  MINEXTENTS 1
  MAXEXTENTS UNLIMITED
  ),
  PARTITION P8 VALUES (8)
  TABLESPACE TAB_CC
  PCTFREE 10
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
  INITIAL 8M
  NEXT 1M
  MINEXTENTS 1
  MAXEXTENTS UNLIMITED
  ),
  PARTITION P9 VALUES (9)
  TABLESPACE TAB_CC
  PCTFREE 10
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
  INITIAL 8M
  NEXT 1M
  MINEXTENTS 1
  MAXEXTENTS UNLIMITED
  ),
  PARTITION P10 VALUES (10)
  TABLESPACE TAB_CC
  PCTFREE 10
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
  INITIAL 8M
  NEXT 1M
  MINEXTENTS 1
  MAXEXTENTS UNLIMITED
  ),
  PARTITION P11 VALUES (11)
  TABLESPACE TAB_CC
  PCTFREE 10
  INITRANS 1
  MAXTRANS 255,
  PARTITION P12 VALUES (12)
  TABLESPACE TAB_CC
  PCTFREE 10
  INITRANS 1
  MAXTRANS 255
)

TABLESPACE TAB_CC
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE
(
INITIAL 64K
NEXT 1M
MINEXTENTS 1
MAXEXTENTS UNLIMITED
);
--ADD COMMENTS TO THE TABLE
COMMENT ON TABLE LOTTERY_UNION_LOTTO
IS '双色球彩号记录表';
--ADD COMMENTS TO THE COLUMNS
COMMENT ON COLUMN LOTTERY_UNION_LOTTO.LUCKY_NUMBER_ID
IS '彩号ID';
COMMENT ON COLUMN LOTTERY_UNION_LOTTO.LOTTERY_DATE
IS '开奖日期';
COMMENT ON COLUMN LOTTERY_UNION_LOTTO.LOTTERY_ISSUE
IS '期号';
COMMENT ON COLUMN LOTTERY_UNION_LOTTO.LOTTERY_TYPE
IS '类型';
COMMENT ON COLUMN LOTTERY_UNION_LOTTO.RED_NUMBER1
IS '红色号码1';
COMMENT ON COLUMN LOTTERY_UNION_LOTTO.RED_NUMBER1_STATUS
IS '红1状态';
COMMENT ON COLUMN LOTTERY_UNION_LOTTO.RED_NUMBER2
IS '红2';
COMMENT ON COLUMN LOTTERY_UNION_LOTTO.RED_NUMBER2_STATUS
IS '红2状态';
COMMENT ON COLUMN LOTTERY_UNION_LOTTO.RED_NUMBER3
IS '红3';
COMMENT ON COLUMN LOTTERY_UNION_LOTTO.RED_NUMBER3_STATUS
IS '红3状态';
COMMENT ON COLUMN LOTTERY_UNION_LOTTO.RED_NUMBER4
IS '红4';
COMMENT ON COLUMN LOTTERY_UNION_LOTTO.RED_NUMBER4_STATUS
IS '红4状态';
COMMENT ON COLUMN LOTTERY_UNION_LOTTO.RED_NUMBER5
IS '红5';
COMMENT ON COLUMN LOTTERY_UNION_LOTTO.RED_NUMBER5_STATUS
IS '红5状态';
COMMENT ON COLUMN LOTTERY_UNION_LOTTO.RED_NUMBER6
IS '红6';
COMMENT ON COLUMN LOTTERY_UNION_LOTTO.RED_NUMBER6_STATUS
IS '红6状态';
COMMENT ON COLUMN LOTTERY_UNION_LOTTO.BLUE_NUMBER
IS '篮1';
COMMENT ON COLUMN LOTTERY_UNION_LOTTO.BLUE_NUMBER_STATUS
IS '蓝1状态';
COMMENT ON COLUMN LOTTERY_UNION_LOTTO.PART_ID
IS '分区字段';

-- CREATE/RECREATE INDEXES
CREATE INDEX IDX_LOTTERY_DATE ON LOTTERY_UNION_LOTTO (LOTTERY_DATE)
LOCAL;
CREATE INDEX IDX_LOTTERY_ISSUE ON LOTTERY_UNION_LOTTO (LOTTERY_ISSUE)
LOCAL;
-- Create sequence
create sequence LUCKY_NUMBER_ID_SEQ
minvalue 1
maxvalue 9999999999
start with 7871
increment by 1
cache 20;