package com.luwei6.lottery.dao;

import com.luwei6.lottery.model.LotteryUnionLottoDto;
import org.springframework.stereotype.Repository;
import org.springframework.stereotype.Service;

public interface LotteryUnionLottoDao {
    int findNextLuckyNumberId();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY_UNION_LOTTO
     *
     * @mbg.generated Fri Oct 26 13:59:25 CST 2018
     */
    int deleteByPrimaryKey(Integer luckyNumberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY_UNION_LOTTO
     *
     * @mbg.generated Fri Oct 26 13:59:25 CST 2018
     */
    int insert(LotteryUnionLottoDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY_UNION_LOTTO
     *
     * @mbg.generated Fri Oct 26 13:59:25 CST 2018
     */
    int insertSelective(LotteryUnionLottoDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY_UNION_LOTTO
     *
     * @mbg.generated Fri Oct 26 13:59:25 CST 2018
     */
    LotteryUnionLottoDto selectByPrimaryKey(Integer luckyNumberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY_UNION_LOTTO
     *
     * @mbg.generated Fri Oct 26 13:59:25 CST 2018
     */
    int updateByPrimaryKeySelective(LotteryUnionLottoDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOTTERY_UNION_LOTTO
     *
     * @mbg.generated Fri Oct 26 13:59:25 CST 2018
     */
    int updateByPrimaryKey(LotteryUnionLottoDto record);
}