package com.luwei6.lottery.model;

import java.util.Date;

public class LotteryUnionLottoDto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY_UNION_LOTTO.LUCKY_NUMBER_ID
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    private Integer luckyNumberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY_UNION_LOTTO.LOTTERY_DATE
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    private Date lotteryDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY_UNION_LOTTO.LOTTERY_ISSUE
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    private String lotteryIssue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY_UNION_LOTTO.LOTTERY_TYPE
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    private Integer lotteryType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY_UNION_LOTTO.RED_NUMBER1
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    private Long redNumber1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY_UNION_LOTTO.RED_NUMBER1_STATUS
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    private String redNumber1Status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY_UNION_LOTTO.RED_NUMBER2
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    private Long redNumber2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY_UNION_LOTTO.RED_NUMBER2_STATUS
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    private String redNumber2Status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY_UNION_LOTTO.RED_NUMBER3
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    private Long redNumber3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY_UNION_LOTTO.RED_NUMBER3_STATUS
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    private String redNumber3Status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY_UNION_LOTTO.RED_NUMBER4
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    private Long redNumber4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY_UNION_LOTTO.RED_NUMBER4_STATUS
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    private String redNumber4Status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY_UNION_LOTTO.RED_NUMBER5
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    private Long redNumber5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY_UNION_LOTTO.RED_NUMBER5_STATUS
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    private String redNumber5Status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY_UNION_LOTTO.RED_NUMBER6
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    private Long redNumber6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY_UNION_LOTTO.RED_NUMBER6_STATUS
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    private String redNumber6Status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY_UNION_LOTTO.BLUE_NUMBER
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    private Long blueNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY_UNION_LOTTO.BLUE_NUMBER_STATUS
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    private String blueNumberStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOTTERY_UNION_LOTTO.PART_ID
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    private Long partId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY_UNION_LOTTO.LUCKY_NUMBER_ID
     *
     * @return the value of LOTTERY_UNION_LOTTO.LUCKY_NUMBER_ID
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    public Integer getLuckyNumberId() {
        return luckyNumberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY_UNION_LOTTO.LUCKY_NUMBER_ID
     *
     * @param luckyNumberId the value for LOTTERY_UNION_LOTTO.LUCKY_NUMBER_ID
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    public void setLuckyNumberId(Integer luckyNumberId) {
        this.luckyNumberId = luckyNumberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY_UNION_LOTTO.LOTTERY_DATE
     *
     * @return the value of LOTTERY_UNION_LOTTO.LOTTERY_DATE
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    public Date getLotteryDate() {
        return lotteryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY_UNION_LOTTO.LOTTERY_DATE
     *
     * @param lotteryDate the value for LOTTERY_UNION_LOTTO.LOTTERY_DATE
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    public void setLotteryDate(Date lotteryDate) {
        this.lotteryDate = lotteryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY_UNION_LOTTO.LOTTERY_ISSUE
     *
     * @return the value of LOTTERY_UNION_LOTTO.LOTTERY_ISSUE
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    public String getLotteryIssue() {
        return lotteryIssue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY_UNION_LOTTO.LOTTERY_ISSUE
     *
     * @param lotteryIssue the value for LOTTERY_UNION_LOTTO.LOTTERY_ISSUE
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    public void setLotteryIssue(String lotteryIssue) {
        this.lotteryIssue = lotteryIssue == null ? null : lotteryIssue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY_UNION_LOTTO.LOTTERY_TYPE
     *
     * @return the value of LOTTERY_UNION_LOTTO.LOTTERY_TYPE
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    public Integer getLotteryType() {
        return lotteryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY_UNION_LOTTO.LOTTERY_TYPE
     *
     * @param lotteryType the value for LOTTERY_UNION_LOTTO.LOTTERY_TYPE
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    public void setLotteryType(Integer lotteryType) {
        this.lotteryType = lotteryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY_UNION_LOTTO.RED_NUMBER1
     *
     * @return the value of LOTTERY_UNION_LOTTO.RED_NUMBER1
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    public Long getRedNumber1() {
        return redNumber1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY_UNION_LOTTO.RED_NUMBER1
     *
     * @param redNumber1 the value for LOTTERY_UNION_LOTTO.RED_NUMBER1
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    public void setRedNumber1(Long redNumber1) {
        this.redNumber1 = redNumber1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY_UNION_LOTTO.RED_NUMBER1_STATUS
     *
     * @return the value of LOTTERY_UNION_LOTTO.RED_NUMBER1_STATUS
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    public String getRedNumber1Status() {
        return redNumber1Status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY_UNION_LOTTO.RED_NUMBER1_STATUS
     *
     * @param redNumber1Status the value for LOTTERY_UNION_LOTTO.RED_NUMBER1_STATUS
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    public void setRedNumber1Status(String redNumber1Status) {
        this.redNumber1Status = redNumber1Status == null ? null : redNumber1Status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY_UNION_LOTTO.RED_NUMBER2
     *
     * @return the value of LOTTERY_UNION_LOTTO.RED_NUMBER2
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    public Long getRedNumber2() {
        return redNumber2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY_UNION_LOTTO.RED_NUMBER2
     *
     * @param redNumber2 the value for LOTTERY_UNION_LOTTO.RED_NUMBER2
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    public void setRedNumber2(Long redNumber2) {
        this.redNumber2 = redNumber2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY_UNION_LOTTO.RED_NUMBER2_STATUS
     *
     * @return the value of LOTTERY_UNION_LOTTO.RED_NUMBER2_STATUS
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    public String getRedNumber2Status() {
        return redNumber2Status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY_UNION_LOTTO.RED_NUMBER2_STATUS
     *
     * @param redNumber2Status the value for LOTTERY_UNION_LOTTO.RED_NUMBER2_STATUS
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    public void setRedNumber2Status(String redNumber2Status) {
        this.redNumber2Status = redNumber2Status == null ? null : redNumber2Status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY_UNION_LOTTO.RED_NUMBER3
     *
     * @return the value of LOTTERY_UNION_LOTTO.RED_NUMBER3
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    public Long getRedNumber3() {
        return redNumber3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY_UNION_LOTTO.RED_NUMBER3
     *
     * @param redNumber3 the value for LOTTERY_UNION_LOTTO.RED_NUMBER3
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    public void setRedNumber3(Long redNumber3) {
        this.redNumber3 = redNumber3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY_UNION_LOTTO.RED_NUMBER3_STATUS
     *
     * @return the value of LOTTERY_UNION_LOTTO.RED_NUMBER3_STATUS
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    public String getRedNumber3Status() {
        return redNumber3Status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY_UNION_LOTTO.RED_NUMBER3_STATUS
     *
     * @param redNumber3Status the value for LOTTERY_UNION_LOTTO.RED_NUMBER3_STATUS
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    public void setRedNumber3Status(String redNumber3Status) {
        this.redNumber3Status = redNumber3Status == null ? null : redNumber3Status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY_UNION_LOTTO.RED_NUMBER4
     *
     * @return the value of LOTTERY_UNION_LOTTO.RED_NUMBER4
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    public Long getRedNumber4() {
        return redNumber4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY_UNION_LOTTO.RED_NUMBER4
     *
     * @param redNumber4 the value for LOTTERY_UNION_LOTTO.RED_NUMBER4
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    public void setRedNumber4(Long redNumber4) {
        this.redNumber4 = redNumber4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY_UNION_LOTTO.RED_NUMBER4_STATUS
     *
     * @return the value of LOTTERY_UNION_LOTTO.RED_NUMBER4_STATUS
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    public String getRedNumber4Status() {
        return redNumber4Status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY_UNION_LOTTO.RED_NUMBER4_STATUS
     *
     * @param redNumber4Status the value for LOTTERY_UNION_LOTTO.RED_NUMBER4_STATUS
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    public void setRedNumber4Status(String redNumber4Status) {
        this.redNumber4Status = redNumber4Status == null ? null : redNumber4Status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY_UNION_LOTTO.RED_NUMBER5
     *
     * @return the value of LOTTERY_UNION_LOTTO.RED_NUMBER5
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    public Long getRedNumber5() {
        return redNumber5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY_UNION_LOTTO.RED_NUMBER5
     *
     * @param redNumber5 the value for LOTTERY_UNION_LOTTO.RED_NUMBER5
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    public void setRedNumber5(Long redNumber5) {
        this.redNumber5 = redNumber5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY_UNION_LOTTO.RED_NUMBER5_STATUS
     *
     * @return the value of LOTTERY_UNION_LOTTO.RED_NUMBER5_STATUS
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    public String getRedNumber5Status() {
        return redNumber5Status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY_UNION_LOTTO.RED_NUMBER5_STATUS
     *
     * @param redNumber5Status the value for LOTTERY_UNION_LOTTO.RED_NUMBER5_STATUS
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    public void setRedNumber5Status(String redNumber5Status) {
        this.redNumber5Status = redNumber5Status == null ? null : redNumber5Status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY_UNION_LOTTO.RED_NUMBER6
     *
     * @return the value of LOTTERY_UNION_LOTTO.RED_NUMBER6
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    public Long getRedNumber6() {
        return redNumber6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY_UNION_LOTTO.RED_NUMBER6
     *
     * @param redNumber6 the value for LOTTERY_UNION_LOTTO.RED_NUMBER6
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    public void setRedNumber6(Long redNumber6) {
        this.redNumber6 = redNumber6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY_UNION_LOTTO.RED_NUMBER6_STATUS
     *
     * @return the value of LOTTERY_UNION_LOTTO.RED_NUMBER6_STATUS
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    public String getRedNumber6Status() {
        return redNumber6Status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY_UNION_LOTTO.RED_NUMBER6_STATUS
     *
     * @param redNumber6Status the value for LOTTERY_UNION_LOTTO.RED_NUMBER6_STATUS
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    public void setRedNumber6Status(String redNumber6Status) {
        this.redNumber6Status = redNumber6Status == null ? null : redNumber6Status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY_UNION_LOTTO.BLUE_NUMBER
     *
     * @return the value of LOTTERY_UNION_LOTTO.BLUE_NUMBER
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    public Long getBlueNumber() {
        return blueNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY_UNION_LOTTO.BLUE_NUMBER
     *
     * @param blueNumber the value for LOTTERY_UNION_LOTTO.BLUE_NUMBER
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    public void setBlueNumber(Long blueNumber) {
        this.blueNumber = blueNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY_UNION_LOTTO.BLUE_NUMBER_STATUS
     *
     * @return the value of LOTTERY_UNION_LOTTO.BLUE_NUMBER_STATUS
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    public String getBlueNumberStatus() {
        return blueNumberStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY_UNION_LOTTO.BLUE_NUMBER_STATUS
     *
     * @param blueNumberStatus the value for LOTTERY_UNION_LOTTO.BLUE_NUMBER_STATUS
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    public void setBlueNumberStatus(String blueNumberStatus) {
        this.blueNumberStatus = blueNumberStatus == null ? null : blueNumberStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOTTERY_UNION_LOTTO.PART_ID
     *
     * @return the value of LOTTERY_UNION_LOTTO.PART_ID
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    public Long getPartId() {
        return partId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOTTERY_UNION_LOTTO.PART_ID
     *
     * @param partId the value for LOTTERY_UNION_LOTTO.PART_ID
     *
     * @mbg.generated Fri Oct 26 17:01:46 CST 2018
     */
    public void setPartId(Long partId) {
        this.partId = partId;
    }
}